### ISSUE TITLE
In C# 3-Party Payment intigration Getting error

### ISSUE THREAD

**Issue by Suraj7814** [americanexpress/amex-api-java-client-core#8]
I am working on C# 3-Party Payment integration.

For amex post i have below parameters.
Field Name | Value
-- | --
vpc_Version | 1
vpc_Command | pay
vpc_AccessCode | XXXXXXX
vpc_MerchTxnRef | 6AQ55F3
vpc_Merchant | TEST1234567890
vpc_OrderInfo | TEST002019
vpc_Amount | 100
vpc_Currency | SGD
vpc_Locale | en

and i have used below function for create hash

 public static string ComputeSha256HashNewString(AMEXModel Model)
        {
            var secureSecret = "BB48A64077A1CBF08FF0D91C5A9FE42B";
            var args = new SortedDictionary<string, string>()
            {
                //{"user_SessionId" , Model.user_SessionId},
                {"vpc_AccessCode" , Model.vpc_AccessCode},
                {"vpc_Amount" , Model.vpc_Amount},
                {"vpc_Command" , Model.vpc_Command},
                {"vpc_Currency" , Model.vpc_Currency},
                {"vpc_Locale" , Model.vpc_Locale},
                {"vpc_Merchant" , Model.vpc_Merchant},
                {"vpc_MerchTxnRef" , Model.vpc_MerchTxnRef},
                {"vpc_OrderInfo" , Model.vpc_OrderInfo},
                {"vpc_ReturnURL" , Model.vpc_ReturnURL},
                {"vpc_Version" , Model.vpc_Version}
            };
            var getPart = "";
            foreach (var arg in args)
            {
                getPart += arg.Key + "=" + arg.Value + "&";
            }
            getPart = getPart.TrimEnd('&');
            var keyBytes = new byte[secureSecret.Length / 2];
            for (int i = 0; i < keyBytes.Length; i++)
            {
                keyBytes[i] = byte.Parse(secureSecret.Substring(i * 2, 2), System.Globalization.NumberStyles.HexNumber);
            }
            var hmac = new HMACSHA256(keyBytes);
            var hash = hmac.ComputeHash(Encoding.ASCII.GetBytes(getPart));
            var hashString = BitConverter.ToString(hash).Replace("-", "");
            return hashString;
        }

after create hash i m trying post url like below.
https://vpos.amxvpos.com/vpcpay?vpc_AccessCode=XXXXXXX&vpc_Amount=100&vpc_Command=pay&vpc_Currency=SGD&vpc_Locale=en&vpc_Merchant=TEST1234567890&vpc_MerchTxnRef=6AQ55F3&vpc_OrderInfo=TEST002019&vpc_ReturnURL=http://localhost:50582/Home/ThankYou&vpc_Version=1&vpc_SecureHash=03358B9D8CD1B34781AD5251BBD8909E3F5E8C7786527AC600FCF925583DB865&vpc_SecureHashType=SHA256

but i am getting below error.
HTTP Status - 400
E5000: Cannot form a matching secure hash based on the merchant's request using either of the two merchant's secrets

Please advice for above issue.

**Comment by AmexAPIGuy** [comment]
Hi Suraj,
A couple things I see.
1) The API you are calling doesn't appear to be one of the Amex primary APIs typically found on the https://api.americanexpress.com/ domain. Therefore it may not use this package for the HMAC generation.
2) for .Net solutions, you could look at the package in our other repo: https://github.com/americanexpress/amex-api-dotnet-client-core
However, if the API is not one of ours or is a legacy API, neither package will solve the problem.

**Comment by Suraj7814** [comment]
i am working on 3 Party online payment gateway.
